# safelist
#branches:
#  only:
#    - master
language: bash

services:
  - docker

before_install:
  - docker pull asciishell/docker-latex
script:
  - docker run -u root --rm  -it -v $(pwd):/source asciishell/docker-latex bash ./build.sh

deploy:
  - provider: releases
    api_key: $TOKEN
    file: "Text/main.pdf"
    skip_cleanup: true
    on:
      branch: master
